Round 2 edits
arfc/2018-westphal-antpc pull request #13
Opened 2018-05-04 23:08 UTC by gtw2

Using this as a place to compile edits - added table.
    > Need to move process detail and explain table still

2018-05-05 00:36 UTC, gtw2 commented
Should I cite papers inside the table of parameters?

2018-05-08 18:18 UTC, katyhuff commented
> Should I cite papers inside the table of parameters?

Yes, if the parameter value came from somewhere you should cite that. A common way is to have a table structure where one of the columns is "Ref." and contains references where the parameters were found.

2018-05-15 12:52 UTC, katyhuff commented
@gtw2 This branch has conflicts. Please resolve them.

2018-05-15 15:53 UTC, katyhuff commented
Do not version this file: reduction.synctex.gz

2018-05-15 15:59 UTC, katyhuff commented
Generally, versioning pdfs is not advised.

2018-05-15 16:26 UTC, katyhuff requested changes

2018-05-15 16:26 UTC, katyhuff commented on winning.tex
> +% Author: Kathryn Huff
I am not the author of this file. Please amend. Say "Authors: Kathryn Huff, Gregory Westphal" or similar.

2018-05-15 16:26 UTC, katyhuff commented on volox.tex
> +% Author: Kathryn Huff
I am not the author of this file. Please amend. Say "Authors: Kathryn Huff, Gregory Westphal" or similar.

2018-05-15 16:26 UTC, katyhuff commented on 2018-westphal-antpc.tex
> +\author{Gregory T. Westphal* and Kathryn D. Huff}
$^*$

2018-05-15 16:26 UTC, katyhuff commented on 2018-westphal-antpc.tex
> +*gtw2@illinois.edu
$^*$

2018-05-15 16:26 UTC, katyhuff commented on 2018-westphal-antpc.tex
> +The separations facility provided by the \Cycamore library is used as an initial model of a simple PRIDE facility.
The pride facility has not been explained and KAERI is no longer mentioned or cited (those parts were deleted?). This is not good.

2018-05-15 16:26 UTC, katyhuff commented
please see #15 for a pr that fixes some of these issues.

2018-05-15 20:17 UTC, katyhuff commented
If you can fix the inline comments in the above review, this can be pulled. Once this is merged, then please move on to #17 .

2018-05-16 02:19 UTC, merged

2018-05-16 12:36 UTC, katyhuff commented
![bitmoji](https://render.bitstrips.com/v2/cpanel/8c15569e-920d-40ca-a005-52d026c9bde5-aef391d1-ee2a-4ffc-b1c7-1c24444a7cae-v1.png?transparent=1&palette=1&width=246)