Issue #21 Changes
arfc/2018-westphal-antpc pull request #22
Opened 2018-07-24 21:23 UTC by gtw2

The following changes are made in this pull request:
- Removes arrows from parameter inputs on charts.
- Changes passive to active voice and removes 'the' and 'that' to remove blending and shorten sentences.
- Adds short intro to reduction and refining, as well as clearing up intro winning sentence (splits into 2 and shortens to clarify). 
- With these changes, graphs were resized back to full size without going over 4 pages.
- Pyre -> PyRe
- Confusing (and unnecessary) sentences deleted: first sentence in abstract and cyclus discrete time.

2018-07-25 13:04 UTC, katyhuff requested changes

2018-07-25 13:04 UTC, katyhuff commented on 2018-westphal-antpc.tex
> +right side of the processes contain the observable waste produced by each step that PyRe tracks.
ambiguous antecedent: Unclear from the sentence phrasing whether PyRes track the observable waste or the steps.

2018-07-25 13:04 UTC, katyhuff commented on 2018-westphal-antpc.tex
> +Explicit behavior of each main process is described below.
The explicit behavior...

2018-07-25 13:04 UTC, katyhuff commented on 2018-westphal-antpc.tex
> +LWR fuel must be treated and separated before proceeding with electrolytic processes. Uranium dioxide heated under
Perhaps "to" rather than "under"

2018-07-25 13:04 UTC, katyhuff commented on 2018-westphal-antpc.tex
> +	\includegraphics[width=1\linewidth]{volox}
pro-tip: if 1 is meant, no number is needed .  `width=\linewidth` is sufficient.

2018-07-25 13:04 UTC, katyhuff commented on 2018-westphal-antpc.tex
> +Oxidant is converted into metallic fuel through electroreduction for use in the proceeding processes. Yellowcake, created in voloxidation, enters the cathode, a negatively charged metal basket. Curre
This sentence is quite confusing. Please try reading it aloud "Oxidant is converted into metallic fuel through electroreduction for use in the proceeding processes." 

Perhaps "The oxidant..." would help... but there's something else about the "for use..." phrase that is very unclear.

2018-07-25 13:04 UTC, katyhuff commented on 2018-westphal-antpc.tex
> +Oxidant is converted into metallic fuel through electroreduction for use in the proceeding processes. Yellowcake, created in voloxidation, enters the cathode, a negatively charged metal basket. Curre
Also, perhaps "Current density" should be "A current density" (I think I highlighted it because C was incorrectly capitalized... not because the A should be deleted)

2018-07-25 13:04 UTC, katyhuff commented on 2018-westphal-antpc.tex
> +This stream has considerable decay signature proportional to the efficiency and size of the feed batch \cite{Borrelli_2017,flowsheet_1998}.
"has a considerable"

2018-07-25 13:04 UTC, katyhuff commented on 2018-westphal-antpc.tex
> +This stream has considerable decay signature proportional to the efficiency and size of the feed batch \cite{Borrelli_2017,flowsheet_1998}.
also, do these refs really work? shouldn't it be `borrelli_word_2017`? Are you exporting the bib from zotero or doing something manually? Is all the metadata there?

2018-07-25 13:04 UTC, katyhuff commented on 2018-westphal-antpc.tex
> +Once in metallic form, electrorefining electrochemically separates uranium and TRUs for fuel fabrication.
For consistency, it's best to use the glossary for all of the acronyms (including TRUs). You can use something like glspl for the plural version.

2018-07-25 13:04 UTC, katyhuff commented on 2018-westphal-antpc.tex
> +In facilities where iron equipment is present, temperatures are limited to 700$^{\circ}$C, and efficiency is significantly hindered.
For brevity/clarity:

"and efficiency is significantly hindered" -> "hindering efficiency"

2018-07-25 13:04 UTC, katyhuff commented on 2018-westphal-antpc.tex
> +The electrorefining process also produces the fission product waste stream which requires monitoring.
Is this the only fission product waste stream? If it's not, then "the fission product waste stream" should be "a fission product waste stream"

2018-07-25 13:04 UTC, katyhuff commented on 2018-westphal-antpc.tex
> +Uranium and TRU product streams separated at this stage are sent to Fuel Fabrication, while the remaining salt is reformed as an oxidant and recirculated.
use glossary for TRU. Why is fuel fabrication capitalized?

2018-07-25 13:04 UTC, katyhuff commented on 2018-westphal-antpc.tex
> +Separation efficiencies are taken after recirculation, and treated as a once-through cycle. Cyclus' time step
You should be clear that you're now talking about your model, not the process.

2018-07-25 13:04 UTC, katyhuff commented on 2018-westphal-antpc.tex
> +Molten salt containing TRUs from electrorefining is separated through electrowinning. This subprocess results in separation of trace uranium quantities, lanthanides and fission products.
"This subprocess results in separation of" -> "This process separates"

2018-07-25 13:04 UTC, katyhuff commented on 2018-westphal-antpc.tex
> +The goal for PyRe is to include facility configuration parameters and their respective effects on the efficiency table.
The table isn't the end goal. The table is a means to an end. What is PyRe's real ultimate goal?

2018-07-25 13:04 UTC, katyhuff commented on 2018-westphal-antpc.tex
> +A test will also be used to verify isotopic efficiencies add up to 1.
"isotopic efficiencies" is meaningless. You should probably just say that "Unit tests and runtime checks will confirm material conservation."

2018-07-25 13:04 UTC, katyhuff commented on 2018-westphal-antpc.tex
> +Efficiencies also vary according to the feed stream resulting in different waste streams for LWR and FR fuels, for example.
This seems like a non sequitur.

2018-07-25 13:04 UTC, katyhuff commented on 2018-westphal-antpc.tex
> +Facility configuration parameters customize the pyroprocessing archetype.
This paragraph reads more like a bulleted list than a paragraph. Try reading it aloud and then rewrite the main idea in conversational english.

2018-07-25 13:04 UTC, katyhuff commented on 2018-westphal-antpc.tex
>  processes are used to verify diversion did not occur. Fuel fabrication is also at high risk of diversion. Finished product can be diverted with no additional
The finished product...

2018-07-25 13:04 UTC, katyhuff commented on 2018-westphal-antpc.tex
> +processing steps and a material balance area is also taken here.
This sentence reads weird. Try reading it aloud.

2018-07-26 04:58 UTC, gtw2 commented
When built at home, the paper is less than 4 pages by a paragraph. At the office, however, it builds a line over 4 pages. Not sure what causes this, will double check in the morning.

2018-07-26 14:23 UTC, katyhuff commented
Does `git status` indicate any difference between the home repository status and the work repository status? It's under 4 pages (by about a paragraph) when I build it.

2018-07-26 14:35 UTC, katyhuff commented on acros.tex
> +\newacronym{PyRe}{PyRe}{Pyroprocessing Repository}
Is that actually what this stands for? For some reason I thought it stood for something like (Py)ro (Re)processing module. Repository is an overloaded term (I assume you mean git repository, but nuclear engineers will assume you mean nuclear repository). Maybe Pyre was better after all... no acroynym needed.

2018-07-26 14:53 UTC, gtw2 commented on acros.tex
> +\newacronym{PyRe}{PyRe}{Pyroprocessing Repository}
Yeah, I wasn't sure what we decided on for the Re portion. I'll change the definition to Pyro Reprocessing (module) instead of Pyroprocessing

2018-07-26 14:54 UTC, gtw2 commented
It builds normally now, did a reboot and its fine.

2018-07-26 14:55 UTC, merged

2018-07-26 14:56 UTC, katyhuff commented
![bitmoji](https://render.bitstrips.com/v2/cpanel/b2adcf31-8a3d-457b-8b87-9ac5aad8d214-aef391d1-ee2a-4ffc-b1c7-1c24444a7cae-v1.png?transparent=1&palette=1&width=246)